curl -X DELETE http://localhost:3000/api/product_types/4
curl -X DELETE http://localhost:3000/api/product_series/5
curl -X DELETE http://localhost:3000/api/commissions/5
curl -X DELETE http://localhost:3000/api/events/3
curl -X DELETE http://localhost:3000/api/expenses/4
curl -X DELETE http://localhost:3000/api/products/5
curl -X DELETE http://localhost:3000/api/sales/6
curl -X DELETE http://localhost:3000/api/sale_line_items/8
curl -X DELETE http://localhost:3000/api/users/3